[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^4^
uuid = {version = "^0.8.2", features = ["v4"]}
serde = {version = "^1.0.125", features = ["derive"]}
diesel = {version = "^1.4.7", features = ["postgres", "r2d2"]}